version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq

  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - features

  metrics:
    build:
      context: ./metrics
    restart: always
    depends_on:
      - model
    volumes:
      - ./logs/:/usr/src/app/logs/

  plot:
    build:
      context: ./plot
    restart: always
    volumes:
      - ./logs/:/usr/src/app/logs/
